DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS files;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  IsAdmin BOOLEAN DEFAULT 0,
  IsSuperAdmin BOOLEAN DEFAULT 0,
  usedStorage BIGINT DEFAULT 0,
  maxStorage BIGINT DEFAULT 1,
  usedDownload BIGINT DEFAULT 0,
  maxDownload BIGINT DEFAULT 1,
  expire_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  filename TEXT NOT NULL,
  file_key TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  file_url TEXT NOT NULL,
  content_type TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
