name: Build - Nuxt 3 (Windows artifact)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (Nuxt SSR/Nitro)
        env:
          NODE_ENV: production
          NUXT_TELEMETRY_DISABLED: 1
        run: npm run build   # 产物在 .output/

      - name: Debug workspace and .output
        shell: pwsh
        run: |
          Write-Host "GITHUB_WORKSPACE = $env:GITHUB_WORKSPACE"
          Get-ChildItem -Force | Select-Object Name,Length,Mode
          if (Test-Path .output) {
            Write-Host ".output exists, sample files:"
            Get-ChildItem -Recurse -Force .output | Select-Object -First 20 FullName
          } else {
            Write-Host ".output NOT FOUND"
          }

      - name: Add Windows start scripts (robust)
        shell: pwsh
        run: |
          if (!(Test-Path .output)) { throw ".output not found" }
          @(
            '@echo off'
            'if "%PORT%"=="" set PORT=3000'
            'if "%NITRO_HOST%"=="" set NITRO_HOST=0.0.0.0'
            'node "%~dp0server\index.mjs"'
          ) | Set-Content -Path ".output\start.bat" -Encoding ASCII

          @(
            'if (-not $env:PORT) { $env:PORT = "3000" }'
            'if (-not $env:NITRO_HOST) { $env:NITRO_HOST = "0.0.0.0" }'
            'node "$PSScriptRoot\server\index.mjs"'
          ) | Set-Content -Path ".output\start.ps1" -Encoding ASCII

      - name: Zip .output
        shell: pwsh
        run: |
          if (!(Test-Path .output)) { throw ".output not found before zip" }
          Compress-Archive -Path .output\* -DestinationPath nuxt-output-windows-node22.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-output-windows-node22
          path: ${{ github.workspace }}/nuxt-output-windows-node22.zip
          if-no-files-found: error
          retention-days: 7
